### ISSUE TITLE
Move Channel to Another Team?

### ISSUE THREAD

**Issue by phreed** [gabrieljackson/mattermost-plugin-wrangler#113]
Wrangler can move a Thread from one Channel to another.
Is it possible to move a Channel from one Team to another?

**Comment by gabrieljackson** [comment]
Hey @phreed, the ability to move a channel to a different team is actually supported by the official `mmctl` management tool for Mattermost: https://docs.mattermost.com/manage/mmctl-command-line-tool.html#mmctl-channel-move

Because moving entire channels to another team has additional considerations, this will be something that won't be supported in Wrangler for now. `mmctl` should be used when this functionality is needed.

Let me know if you have any other questions.
