### ISSUE TITLE
Messages cannot be moved

### ISSUE THREAD

**Issue by jprusch** [gabrieljackson/mattermost-plugin-wrangler#141]
A message to contact the admin is displayed.

The following messages are printed to server log:

error [2022-08-16 08:52:26.639 +02:00] unable to re-upload file: DoUploadFile: File rejected by plugin. File Blocker plugin - There was an error retrieving the session information,  caller="app/plugin_api.go:975" plugin_id=com.mattermost.wrangler

We've got the Flie Blocker plugin active, but never got any problems inserting images. This could be related to image files handled differently, when pasted/uploaded in contrast to be moved by Wrangler.

**Comment by jprusch** [comment]
The File Blocker setting allows png/jpeg/jpg and so on, BUT requires an extension to the file.

**Comment by gabrieljackson** [comment]
@jprusch I just took a look at the file blocker plugin and the issue seems to be that it expects a normal user session: https://github.com/muratbayan/mattermost-file-blocker/blob/master/server/plugin.go#L43-L48

Wrangler has direct API access to the server without the need for a normal session. I don't want to add complexity around the file copying process, so if you still have interest in resolving this issue you will need to reach out to the maintainer(s) of the File Blocker plugin to see if they can modify the session expectations.
