### ISSUE TITLE
`/wrangler list messages` missing indentions on messages with returns.

### ISSUE THREAD

**Issue by jfrerich** [gabrieljackson/mattermost-plugin-wrangler#24]
### Summary 
When using `/wrangler list messages`, and a message has a return, account for the additional spaces needed to indent by len(UID) + len(" -")

Additionally, add a test for this situation.

**Comment by gabrieljackson** [comment]
I took a slightly different approach to resolving this issue, where I convert message content containing a newline so that newlines are ` | `. The idea here is I can keep the list easier to read while hopefully still providing an easy-enough-to-read summary.

Let me know if you think that covers your initial concern properly or not.

**Comment by gabrieljackson** [comment]
Going to close this and will reopen if necessary.
