### ISSUE TITLE
Allows selecting the channel to move a thread to via channel name

### ISSUE THREAD

**Issue by hanzei** [gabrieljackson/mattermost-plugin-wrangler#38]
Instead of having to look up the channel id, a user should be able to select the channel by name, e.g. `/wrangler move thread [MESSAGE_ID] ~town-square`.

**Comment by gabrieljackson** [comment]
Sounds good! I will look into it.

**Comment by gabrieljackson** [comment]
With the addition of the webapp functionality to Wrangler, I am wondering if this behavior is still desirable or not. The slash commands are the interface that the webapp uses to move and copy threads, so I would like to keep them as simple as is reasonable. Also, I am guessing that most people would just use the webapp now anyway.

Have any thoughts on this @hanzei? I still see the value in this, just wondering if maybe you think the webapp has made this mostly obsolete?

**Comment by gabrieljackson** [comment]
I am still leaning towards keeping the `move thread` slash command straightforward and relying on the web interface to provide the ease-of-use that most users will need. Feel free to let me know if you still see a lot of value in this though!

**Comment by tshirtman** [comment]
Sorry for necroposting (but hey, Halloween is getting close), but came here because, moving a thread to a different channel is a common use case (plausibly the most common?) that could be made very easy.

posting as an answer to the thread.

`/wrangler move thread ~channel-name` should be all the info wrangler needs to do the action, without having to activate and open the UI. I understand it does add complexity, so up to you, but i think there is some value.
